version: '3.8'

services:
  postgres_service:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgre
      POSTGRES_PASSWORD: password
